extractMetadata/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('metadata.urls')),
    path('', include('django.contrib.auth.urls')),
    path('download/<path>', serve,
         {"document_root": settings.MEDIA_ROOT})
]
handler404 = 'metadata.views.error_404'
handler500 = 'metadata.views.error_500'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

metadata/urls.py
from imp import get_magic
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'metadata'
urlpatterns = [
    path("", views.index, name="index"),
    path("about", views.about, name="about"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("signup", views.signup, name="signup"),
    path("profile/<int:pk>", views.profile.as_view(), name="profile"),
    path("viewMetadata", views.view_metadata.as_view(), name="viewMetadata"),
    path("contact", views.contact, name="contact"),
    path("download", views.download_csv_data, name="download"),
    path("result", views.result, name="result"),
    path("save", views.save, name="save"),
    path("saved_files", views.saved_files.as_view(), name="saved_files"),
    path("review/<int:pk>", views.review, name="review"),
    path("history/<int:pk>", views.history.as_view(), name="history"),
    path("change_email/<int:pk>", views.change_email.as_view(), name="change_email"),
    path("update_picture", views.accountSettings, name='update_picture'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path("delete/<int:pk>", views.delete),
    path("delete_meta/<int:pk>", views.delete_meta, name="delete_meta"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("referral/<int:pk>/<int:ak>", views.referral, name="referral"),
    path("download_meta/<int:pk>", views.download_meta, name="download_meta")
]

metadata/models.py
from bz2 import compress
from re import M
from stat import FILE_ATTRIBUTE_HIDDEN
from tkinter import N
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings


class Contact(models.Model):
    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(
            2, "Name must be greater than 2 characters")]
    )
    email = models.CharField(max_length=200)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if len(self.message) < 15:
            return self.message
        return self.text[:11] + ' ...'


class Profile(models.Model):
    # Delete profile when user is deleted
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(
        default='default.jpg', upload_to='profile_pics', null=True, blank=True)

    def __str__(self):
        # show how we want it to be displayed
        return f'{self.user.username} Profile'


class History(models.Model):
    name = models.CharField(max_length=200)
    #size = models.IntegerField()
    data = models.TextField(null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Files(models.Model):
    file_name = models.CharField(max_length=200)
    uploaded_file = models.FileField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,
                              on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.file_name


class other(models.Model):
    pass

metadata/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Profile


class FileUpload(forms.Form):
    upload_file = forms.FileField()


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']

metadata/views.py
from posixpath import basename
import re
from urllib import response
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.urls import reverse_lazy, reverse
import os

from hachoir.parser import createParser
from hachoir.metadata import extractMetadata
import json
from django.http import JsonResponse
from django.http import HttpResponse
from django.utils.encoding import smart_str
from metadata.models import Contact, History, Files
from django.http import HttpResponseRedirect
from .forms import FileUpload, ProfileForm
from extractMetadata import settings

# import helper function defined in helper_functions.py
from .helperFuncs.extractImage import extract_image_metadata
from .helperFuncs.extractPdf import extract_pdf_file
from .helperFuncs.defaultMetadata import default_metadata
# from helperFuncs.pillow import extract_image_metadata_with_pillow

# ================
# import for csv
import csv

# Create your views here.

# =========
# import jsson to save the results
import json
# ===


def index(request):
    context = {}
    if request.method == 'POST':
        username = request.POST['username']
        context = {'username': username}
    return render(request, "index.html", context)


# ==============================================
# =============================================
def about(request):
    return render(request, "about.html")


# ==========================================

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/dashboard')
        else:
            messages.info(request, 'Invalid username or password')
            return redirect('metadata:login')
    return render(request, "login.html")


# ============================================
# ============================================


def logout(request):
    auth.logout(request)
    return redirect('/')


# =============================================
# =============================================


def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        pass2 = request.POST['pass2']
        email = email.lower()
        if password == pass2:
            if User.objects.filter(email=email).exists():
                messages.info(request, "Email already exist")
                return redirect('metadata:signup')
            elif User.objects.filter(username=username).exists():
                messages.info(request, "Username already exist")
                return redirect('metadata:signup')
            else:
                user = User.objects.create_user(
                    username=username, first_name=first_name, last_name=last_name, email=email, password=password)
                user.save()
                messages.info(request, "Account created")
                return HttpResponseRedirect("login")
        else:
            messages.info(request, "Password didnt match")
            return redirect('metadata:signup')

    return render(request, "signup.html")

#======================================================#
# ============== DASHBOARD ============================#
#======================================================#


def dashboard(request):
    return render(request, "profile.html")

# =================================================


class profile(LoginRequiredMixin, View):
    login_url = '/login'
    success_url = reverse_lazy('metadata:profile')
    model = User
    template_name = 'profile.html'

    def get(self, request, pk):
        user = get_object_or_404(User, id=pk)
        return render(request, self.template_name)

    def post(self, request, pk):
        if request.POST['type'] == '1':
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            if len(first_name) < 1 or len(last_name) < 1:
                messages.info(request, "Field cannot be empty")
                return redirect('metadata:profile', pk=pk)
            User.objects.filter(id=pk).update(
                first_name=first_name, last_name=last_name)
            messages.info(request, "Update Succcessful")
            return redirect('metadata:profile', pk=pk)
        else:
            username = request.POST['username']
            password1 = request.POST['pass1']
            password2 = request.POST['pass2']
            if len(password1) < 1 or len(password2) < 1:
                messages.info(request, "Field cannot be empty")
                return redirect('metadata:profile', pk=pk)
            if password1 == password2:
                u = User.objects.get(username=username)
                u.set_password(password1)
                u.save()
                messages.info(request, "Password updated!!")
                user = auth.authenticate(username=username, password=password1)
                if user is not None:
                    auth.login(request, user)
                    return redirect('metadata:profile', pk=pk)

            else:
                messages.info(request, "Password did not match!!")
                return redirect('metadata:profile', pk=pk)


# ===========================================
# ==========================================

def contact(request):
    if request.method == 'POST':
        contact = Contact(
            name=request.POST['name'], email=request.POST['email'], message=request.POST['message'])
        contact.save()
        messages.info(request, "Message sent")
        return redirect('metadata:index')
    return render(request, "contact.html")

# ==========================================
# ==========================================


class view_metadata(LoginRequiredMixin, View):
    success_url = reverse_lazy('metadata:viewMetadata')
    # template_name = 'metadata.html'
    template_name = 'extract.html'
    login_url = '/login'
    REDIRECT_FIELD_NAME = 'next'

    def post(self, request):
        form = FileUpload(request.POST, request.FILES)
        context = {"metadata": []}

        print("=====================")
        if form.is_valid():

            uploaded_file = request.FILES['upload_file']
            file_type = uploaded_file.content_type.split("/")
            print(uploaded_file)

            if file_type[0] == "video" or file_type[0] == "image" or file_type[0] == "audio":

                extracted_metadata = extract_image_metadata(
                    file_type[0], uploaded_file)
                context['metadata'] += extracted_metadata

            elif file_type[1].lower() == "pdf":
                pdf_metadata = extract_pdf_file(uploaded_file)
                context['metadata'] += pdf_metadata

            else:
                context['metadata'] += default_metadata(uploaded_file)

            request.session["metadata"] = context

            if uploaded_file.size < 20000000:
                name = uploaded_file.name
                owner = request.user
                file = Files.objects.filter(file_name=name).exists()

                if not file:
                    data = Files(file_name=name,
                                 uploaded_file=uploaded_file, owner=owner)
                    data.save()

            return redirect("metadata:result")
        return render(request, self.template_name, {'form': form})

    def get(self, request):
        form = FileUpload()
        return render(request, self.template_name, {'form': form})

# ================================================
# ================================================


def result(request):
    metadata = request.session.get("metadata")
    context = metadata
    return render(request, "result.html", context)


# ============================================
# ============================================
def save(request):
    metadata = request.session.get("metadata")
    name = metadata['metadata'][0]['tag_value']
    owner = request.user
    if History.objects.filter(name=name).exists() and History.objects.get(name=name).owner == owner:
        messages.info(request, "Data already present in your save history")
        return render(request, "profile.html")
    else:
        data = json.dumps(metadata)
        history = History(data=data, name=name, owner=owner)
        history.save()
        messages.info(request, "data saved succesfully")
        return render(request, "profile.html")

# ================


class saved_files(LoginRequiredMixin, View):
    login_url = '/login'
    model = Files
    template_name = 'saved_files.html'

    def get(set, request):
        owner = request.user
        files = Files.objects.all()
        context = {"owner": owner, "files": files}
        return render(request, "saved_files.html", context)


# ==============

def delete(request, pk):
    file = Files.objects.get(id=pk)
    file.delete()
    messages.info(request, f"file deleted succesfully")
    return redirect("/saved_files")

# ===============


def delete_meta(request, pk):
    file = History.objects.get(id=pk)
    file.delete()
    owner = request.user
    pk = owner.id
    messages.info(request, f"file deleted succesfully")
    return redirect('metadata:history', pk=pk)

# ======


def download(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path) as fh:
            response = HttpResponse(

metadata/templates/change_email.html
{% extends "base.html" %}
{% load static %}



{% block styles %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
<link rel="stylesheet" href="{% static 'notification.css' %}">
<title>Change Email Address</title>
{% endblock %}

{% block nav %}

<div class="navigation">
	<nav class="menu">
		<a href="/">Home</a>
		<a href="/about">About Us</a>
		<a href="/viewMetadata">Extract Metadata</a>
		<a href="/dashboard" class="active">Dashboard</a>
	</nav>
</div>

{% endblock %}

{% block title %}Profile Page{% endblock%}
{% block content %}

<div class="profile-wrapper">
	<div class="content-section">
		<div class="media">
			{% if user.profile.profile_pic %}
			<img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}" width="200" height="200" />
			{% else %}
			<img class="rounded-circle account-img" src="{% static 'metadata/images/default.jpg'%}" width="200"
				height="200" />
			{% endif %}
		</div>
		<a class="profile-edit" href="/update_picture">Edit Profile Picture</a>

		<div class="profile-link link-active">
			<img src="/static/images/user.png" alt="">
			<a href="/dashboard">Account</a>
		</div>
		<div class="profile-link">
			<img src="/static/images/data-black.svg" alt="">
			<a href="{% url 'metadata:history' user.id %}">Saved Metadata</a>
		</div>
		<div class="profile-link">
			<img src="/static/images/archive-tick.svg" alt="">
			<a href="{% url 'metadata:saved_files' %}">Saved Files</a>
		</div>
	</div>
	<div id="sm-hamburger">
		<img src="/static/images/menu-light.svg" alt="">
		<span>profile nav</span>
	</div>
	<div class="content-section-sm">
		<img src="/static/images/close-circle.svg" alt="" id="sm-hamburger-close">
		<div class="media">
			{% if user.profile.profile_pic %}
			<img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}" width="200" height="200" />
			{% else %}
			<img class="rounded-circle account-img" src="{% static 'metadata/images/default.jpg'%}" width="200"
				height="200" />
			{% endif %}
		</div>
		<a class="sm-profile-edit" href="/update_picture">Edit Profile Picture</a>

		<div class="sm-profile-link sm-link-active">
			<a href="/dashboard">
				<img src="{% static 'images/user.png'  %}" alt="">
			</a>
		</div>
		<div class="sm-profile-link">
			<a href="{% url 'metadata:history' user.id %}">
				<img src="/static/images/data-black.svg" alt="">
			</a>
		</div>
		<div class="sm-profile-link">
			<a href="{% url 'metadata:saved_files' %}">
				<img src="/static/images/archive-tick.svg" alt="">
			</a>
		</div>
	</div>

	<div class="form-wrapper">
		<div class="head">
			<h3>Change Email Address</h3>
		</div>
		<div class="form">
			<div>
				<form action="{% url 'metadata:profile' user.id %}" method="POST">
					{% csrf_token %}
					<label for="email">Enter New Email Address</label><br />
					<input type="email" placeholder="{{ user.email }}" name="new_email" required/><br />
					<label for="last_name">Confirm Email Address</label><br />
					<input type="text" placeholder="{{ user.email }}" name="email2" required/><br />
					<input type="submit" value="Save Changes" class="submit" />
				</form>
			</div>
		</div>
	</div>
</div>



{% endblock %}

<body>
	<div class="password">
		<h1 class="fp1">Change email address</h1>
		<!--form-->
		<form class="myform">
			<div class="meta-form-field">
				<label for="email" class="field-label">Enter New Email Address</label>
				<input type="email" name="email" id="" placeholder="Email">
			</div>
			<form class="myform">
				<div class="meta-form-field">
					<label for="email" class="field-label">Confirm New Email Address</label>
					<input type="email" name="email" id="" placeholder="Email">
				</div>
				<center> <button class="nav-btn-solid">
						<a href="">Save Changes
					</button>
	</div>
	</div>



<h2>Enter your new email below</h2>
{% for message in messages %}
<h5>{{message}}</h5>
{% endfor %}
<form action="{% url 'metadata:change_email' user.id %}" method="POST">
	{% csrf_token %}
	<label for="new_email">Enter your New email</label><br />
	<input type="text" name="new_email" /><br />
	<input type="submit" value="Change Email" /><br />
</form>

metadata/templates/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>MetaData Extractor | Get detailed information on your files</title>
	<link rel="stylesheet" href="{% static 'css/main.css'%}" />
	<link rel="stylesheet" href="{% static 'css/font.css'%}"/>
	<link rel="stylesheet" href="{% static 'css/login.css'%}"/>
	<link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800,500,700,400,900&display=swap" rel="stylesheet">
</head>

<body>
	<section class="autentication-form">
		<div class="left-column" id="login-left">
			<img src="{% static 'images/login-bg.png' %}" alt="" />
		</div>
		<div class="right-column">
			<div class="form-header">
				<h1>Send Us a Message Today</h1>
				<p>Email us at support@deevr.com or use the form below</p>
				{% for message in messages %}
				<h5>{{message}}</h5>
				{% endfor %}
			</div>

			<form action="/contact" method="post">
				{% csrf_token %}
				<div class="form-field">
					<label for="name" class="field-label">Full Name</label>
					<input type="text" name="name" placeholder="Full Name" required />
				</div>
				<div class="form-field">
					<label for="email" class="field-label">Email Address</label>
					<input type="email" name="email" placeholder="Email Address" required />
				</div>
				<br>
				<div class="form-field">
					<label for="message" class="field-label">Leave Us a Message</label>
					<input type="textarea" name="message" required  placeholder="Leave a Message"/><br />
				</div>

				<p class="login-password"><a href="{% url 'metadata:password_reset' %}"></a></p>

				<input type="submit" value="Send Message" />
				<input type="hidden" name="next" value="{{ next }}" />
			</form>
		</div>
	</section>
</body>

</html>

metadata/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>MetaData Extractor | Get detailed information on your files</title>
	<link rel="stylesheet" href="{% static 'css/main.css' %}" />
	<link rel="stylesheet" href="{% static 'css/font.css' %}">
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	<link rel="stylesheet" href="{% static 'css/message.css' %}">
	<link href="https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@800,500,700,400,900&display=swap" rel="stylesheet">
</head>

<body>
	<section class="autentication-form">
		<div class="left-column" id="login-left">
			<img src="../../static/images/login-bg.png" alt="" />
		</div>
		<div class="right-column">
			<div class="form-header">
				<h1>Login</h1>
				<a href="/accounts/google/login/?process=login">
					<img src="../../static/images/google.png" alt="" class="google" />
					Sign in with Google
				</a>
				<a href="/accounts/github/login/?process=login">
					<img src="../../static/images/github.png" alt="" class="fb" />
					Sign in with Github
				</a>
			</div>

			<div class="line">
				<hr> Or
				<hr>
			</div>
			{% for message in messages %}
				<div class="login-model">
				    <div class="login-model-txt">
				        <img src="{% static 'images/close-circle.png' %}" alt="">
				        <div>
				            <!-- <h5>Error</h5> -->
				            <p>{{message}}</p>
				        </div>
				    </div>
				    <!-- <img id="close-hamburger" src="{% static 'images/close-circle1.png' %}" alt=""> -->
				</div>
			{% endfor %}
			<form action="login" method="post">
				{% csrf_token %}
				<div class="form-field">
					<label for="username" class="field-label">Username</label>
					<input type="text" name="username" placeholder="username" required/>
				</div>
				<div class="form-field">
					<label for="password" class="field-label">Password</label>
					<input type="password" name="password" placeholder="Password" id="psw" required/>
					<span class="eye" onclick="myFunction()">
						<img src="../../static/images/eye.png" alt="" class="psw-icon" id="hide" />
						<img src="../../static/images/eye-slash.png" alt="" class="psw-icon" />
					</span>
				</div>

				<p class="login-password"><a href="{% url 'metadata:password_reset' %}"> Forgot Password</a></p>

				<input type="submit" value="Login" />
				<input type="hidden" name="next" value="{{ next }}" />
			</form>

			<div>
				<p class="login-text">Don't have an account? <a href="signup"> Create Account</a></p>
			</div>
		</div>
	</section>


	<script>
		const loginModel = document.querySelector(".login-model")
		const closeLoginModel = document.querySelector("#close-hamburger")
		closeLoginModel.addEventListener("click", () => {
			loginModel.style.display = "none"
		})
	</script>
</body>

</html>

metadata/templates/saved.html
{% extends "dashboardBase.html" %}

{% load static %}
{% block styles %}
<link rel="stylesheet" href="../../static/css/profile.css" />
{% endblock %}

{% block nav %}

<div class="navigation">
    <nav class="menu">
        <a href="/">Home</a>
        <a href="/about">About Us</a>
        <a href="/viewMetadata">Extract Metadata</a>
        <a href="/dashboard" class="active">Dashboard</a>
    </nav>
</div>

{% endblock %}

{% block mobilenav %}

<ul class="sm-menu">
    <li>
        <img src="/static/images/home-2.svg" alt="">
        <a href="/">Home</a>
        <img id="arrow" src="/static/images/arrow-right-light.svg" alt="">
    </li>

    {% if user.is_authenticated %}
    <li>
        <img src="/static/images/data.svg" alt="">
        <a href="/viewMetadata" class="active">Extract Metadata</a>
        <img id="arrow" src="/static/images/arrow-right-light.svg" alt="">
    </li>
    <li class="sm-active">
        <img src="/static/images/user-dark.png" alt="">
        <a href="/dashboard">Dashboard</a>
        <img id="arrow" class="dashboard-arrow" src="/static/images/arrow-right.svg" alt="">
    </li>
    <ul class="sm-profile-link-wrapper">

        <li class="sm-profile-link">
            <img src="../../static/images/user.png" alt="">
            <a href="/dashboard">Account</a>
        </li>
        <li class="sm-profile-link sm-link-active">
            <img src="../../static/images/data-black.svg" alt="">
            <a href="{% url 'metadata:history' user.id %}">Saved Metadata</a>
        </li>
        <li class="sm-profile-link">
            <img src="../../static/images/archive-tick.svg" alt="">
            <a href="{% url 'metadata:saved_files' %}">Saved Files</a>
        </li>
    </ul>
    {% endif %}
    <li>
        <img src="/static/images/people.svg" alt="">
        <a href="/about">About Us</a>
        <img id="arrow" src="/static/images/arrow-right-light.svg" alt="">
    </li>
</ul>

{% endblock %}




{% block content %}


<div class="profile-wrapper">

    <div class="content-section">
        <div class="media">
            {% if user.profile.profile_pic %}
            <img class="rounded-circle account-img" src="{{ user.profile.profile_pic.url }}" width="200" height="200" />
            {% else %}
            <img class="rounded-circle account-img" src="{% static 'metadata/images/default.jpg'%}" width="200"
                height="200" />
            {% endif %}
        </div>
        <a class="profile-edit" href="/update_picture">Edit Profile Picture</a>

        <div class="profile-link">
            <img src="../../static/images/user.png" alt="">
            <a href="/dashboard">Account</a>
        </div>
        <div class="profile-link link-active">
            <img src="../../static/images/data-black.svg" alt="">
            <a href="{% url 'metadata:history' user.id %}">Saved Metadata</a>
        </div>
        <div class="profile-link">
            <img src="../../static/images/archive-tick.svg" alt="">
            <a href="/saved_files">Saved Files</a>
        </div>
        <div class="profile-sign-out">
            <img src="/static/images/logout.svg" alt="">
            <input id="signout-btn" type="button" value="SignOut">
        </div>
    </div>


    <br>

    <div class="form-wrapper" id="file-content_content">
        <div class="head">
            <h1>Saved Metadata</h1>
            {% for message in messages %}
            <h5>{{message}}</h5>
            {% endfor %}
            <!-- SHARE URL MODEL -->
            
            <div class="url-model">
                <div class="model-txt">
                    <img src="{% static 'images/tick-circle.png' %}" alt="">
                    <div>
                        <p>URL copied to clipboard</p>
                    </div>
                </div>
                <img id="close-hamburger" src="{% static 'images/close-circle1.png' %}" alt="">
            </div>

        </div>

        <script>
      
        </script>

        <table>
            <thead>
                <tr>
                    <th colspan="">Date</th>
                    <th colspan="3">File Name</th>
                    <th colspan="4"></th>
                </tr>

            </thead>

            <tbody>

                {% for i in history %}
                {% if i.owner == user%}
                <tr>
                    <td colspan="2">{{i.created_at}}</td>
                    <td colspan="2">{{i.name}}</td>
                    <td><a href="{% url 'metadata:download_meta' i.id %}">Download</a></td>
                    <td><a href="{% url 'metadata:delete_meta' i.id %}">Delete</a></td>
                    <td><a href="{% url 'metadata:review' i.id %}">View</a></td>
                    <td>
                        <a id="share" data-id="{{i.id}}" data-user="{{user.id}}" data-value="{{i.name}}">Share</a>
                        <input id="input" type="text">
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>

        </table>

    </div>

</div>
<!-- MODEL -->
<div class="sign-up-model">
    <div class="sign-up-wrapper">
        <img src="{% static 'images/icon-close.svg' %}" alt="">
        <h5>Sign Out</h5>
        <p>Are you sure you want to sign out?</p>
        <div class="signout-model-btn">
            <a href="{% url 'metadata:history' user.id %}">No</a>
            <a href="/logout">Yes</a>
        </div>
    </div>
</div>


<!-- <div class="sign-up-model">
    <div class="sign-up-wrapper">
        <img src="{% static 'images/icon-close.svg' %}" alt="">
        <h5>Sign Out</h5>
        <p>Are you sure you want to sign out?</p>
        <div class="signout-model-btn">
            <a href="{% url 'metadata:history' user.id %}">No</a>
            <a href="/logout">Yes</a>
        </div>
    </div>
</div> -->

<!-- <div class="url-model">
    <div class="model-txt">
        <img src="{% static 'images/tick-circle.png' %}" alt="">
        <div>
            <h5>Success</h5>
            <p>URL copied to clipboard</p>
        </div>
    </div>
    <img id="close-hamburger" src="{% static 'images/close-circle1.png' %}" alt="">
</div> -->

{% endblock %}



{% block jsScript %}
<script>
    const signOutBtn = document.querySelector("#signout-btn")
    const model = document.querySelector(".sign-up-model")
    const closeIcon = document.querySelector(".sign-up-wrapper img")
    const closeShareNotificationIcon = document.querySelector("#close-hamburger");
    const urlModel = document.querySelector(".url-model")


    signOutBtn.addEventListener("click", () => {
        model.classList.toggle("show-model")
    })
    closeIcon.addEventListener("click", () => {
        model.classList.remove("show-model")
    })

    const shareBtns = document.querySelectorAll("#share")
    shareBtns.forEach(btn => {
        btn.addEventListener("click", () => {
            const id = btn.dataset.id
            const user = btn.dataset.user
        console.log("click")

        urlModel.style.display = "flex"
            console.log(copy(id, user))

        })
    })

    closeShareNotificationIcon.addEventListener("click", () => {
        urlModel.style.display = "none"
    }) 


    function copy(a, b) {
        let copyText = document.querySelector("#input")
        copyText.value = `www.deevr.zurifordummies.com/referral/${a}/${b}`
        copyText.select();
        document.execCommand('copy')
        console.log('Copied Text')
        return copyText
    }

</script>

<script src="/static/javascript/savedFiles.js"></script>
{% endblock %}